@extends('layouts.app')

@section('title', 'Mon pointage')

@section('content')
    <div class="mx-auto max-w-4xl">
        <section class="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-900/60 p-6 sm:p-8">
            <p class="text-sm font-semibold tracking-wide text-emerald-300">ESPACE SALARIÉ</p>
            <div class="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 class="text-3xl font-bold tracking-tight text-white">Bonjour, {{ $employee->name }}.</h1><p class="mt-2 text-slate-400">Scannez le QR affiché par votre responsable pour enregistrer votre arrivée ou votre départ.</p></div><span class="w-fit rounded-full bg-emerald-400/10 px-3 py-1.5 text-sm font-semibold text-emerald-200">Compte actif</span></div>
        </section>

        <section class="mt-6 grid gap-5 md:grid-cols-[1.2fr_.8fr]">
            <article class="rounded-2xl border border-emerald-400/30 bg-emerald-400/5 p-6"><p class="text-sm font-semibold text-emerald-300">POINTER MAINTENANT</p><h2 class="mt-2 text-2xl font-bold text-white">Scanner le QR affiché sur place</h2><p class="mt-2 leading-6 text-slate-300">Le responsable RH génère le QR et l’affiche à l’entrée, sur son ordinateur, une tablette ou un écran. Approchez votre téléphone de cet écran, puis lancez le scan ci-dessous.</p><button id="scan-button" class="mt-6 w-full rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-slate-950 transition hover:bg-emerald-300">Scanner le QR affiché par le RH</button><div id="qr-reader" class="mt-4 overflow-hidden rounded-xl"></div><p id="scan-status" class="mt-3 text-center text-sm text-slate-300" aria-live="polite"></p></article>
            <aside class="rounded-2xl border border-slate-800 bg-slate-900 p-6"><p class="text-sm font-semibold text-blue-300">COMMENT ÇA MARCHE ?</p><ol class="mt-4 space-y-4 text-sm leading-6 text-slate-300"><li class="flex gap-3"><span class="grid size-6 shrink-0 place-items-center rounded-full bg-blue-500/15 font-semibold text-blue-200">1</span><span>Le RH affiche un QR d’arrivée ou de départ au point de contrôle.</span></li><li class="flex gap-3"><span class="grid size-6 shrink-0 place-items-center rounded-full bg-blue-500/15 font-semibold text-blue-200">2</span><span>Vous ouvrez l’application installée sur votre téléphone et scannez ce QR.</span></li><li class="flex gap-3"><span class="grid size-6 shrink-0 place-items-center rounded-full bg-blue-500/15 font-semibold text-blue-200">3</span><span>Vous autorisez votre position puis confirmez le pointage.</span></li></ol><p class="mt-5 rounded-lg border border-slate-700 bg-slate-950/50 p-3 text-xs leading-5 text-slate-400">Le QR n’est pas envoyé individuellement : il est le même pour les salariés présents et expire automatiquement.</p></aside>
        </section>

        <section class="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6"><div class="flex items-center justify-between"><div><h2 class="text-xl font-bold text-white">Mes pointages d’aujourd’hui</h2><p class="mt-1 text-sm text-slate-400">Historique de la journée en cours.</p></div><span class="text-sm text-slate-500">{{ $todayRecords->count() }} action{{ $todayRecords->count() > 1 ? 's' : '' }}</span></div><div class="mt-5 divide-y divide-slate-800">@forelse($todayRecords as $record)<div class="flex items-center justify-between gap-4 py-4"><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-full {{ $record->type === 'arrival' ? 'bg-emerald-400/15 text-emerald-200' : 'bg-amber-400/15 text-amber-200' }}">{{ $record->type === 'arrival' ? '↗' : '↘' }}</span><div><p class="font-semibold text-white">{{ $record->type === 'arrival' ? 'Arrivée enregistrée' : 'Départ enregistré' }}</p><p class="text-sm text-slate-400">{{ $record->pointed_at->format('H:i:s') }} · {{ $record->accuracy_meters ? 'précision ± '.$record->accuracy_meters.' m' : 'précision non transmise' }}</p></div></div><span class="text-sm text-emerald-300">Validé</span></div>@empty<div class="py-8 text-center text-sm text-slate-400">Vous n’avez encore aucun pointage aujourd’hui.</div>@endforelse</div></section>
    </div>
@endsection
